@extends('layouts.site')
@section('title', $doctor->name.' | '.__('site.sample_profile').' | Turkelite Medcare')
@section('description', $doctor->summary ?: __('site.presentation_notice'))
@section('robots', 'noindex,follow')
@php($initials = collect(preg_split('/\s+/',$doctor->name))->filter()->take(-2)->map(fn($p)=>mb_substr($p,0,1))->implode(''))
@section('content')
<section class="v109-profile-hero"><div class="v104-container v109-profile-grid"><div><div class="v109-avatar">{{ $initials }}</div><p class="v104-kicker">{{ __('site.sample_profile') }}</p><h1>{{ $doctor->name }}</h1><p>{{ $doctor->summary ?: $doctor->designation }}</p>@if($doctor->clinic)<p><strong>{{ $doctor->clinic->name }}</strong> · {{ $doctor->clinic->location }}</p>@endif<div class="v104-actions"><a class="v104-btn v104-btn-dark" href="{{ route('treatment-plan') }}">{{ __('site.generic_enquiry') }} ↗</a><a class="v104-btn v104-btn-plain" href="{{ route('doctors.index') }}">{{ __('site.doctors') }} →</a></div></div><figure class="v109-human-card"><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="Clinician and patient reviewing a care plan" fetchpriority="high"><figcaption><small>{{ __('site.publication_gate') }}</small><strong>{{ __('site.before_publication') }}</strong><p>{{ __('site.profile_not_endorsement') }}</p></figcaption></figure></div></section>
<section class="v104-section"><div class="v104-container"><div class="v109-section-head"><div><p class="v104-kicker">{{ __('site.publication_gate') }}</p><h2>{{ __('site.before_publication') }}</h2></div><div><p>{{ __('site.verification_intro') }}</p></div></div><div class="v104-check-grid">@foreach([__('site.verify_clinician'),__('site.verify_facility'),__('site.verify_followup'),__('site.verify_commercial')] as $check)<article><span>0{{ $loop->iteration }}</span><h3>{{ __('site.publication_gate') }}</h3><p>{{ $check }}</p></article>@endforeach</div></div></section>
@if($doctor->treatments->isNotEmpty())<section class="v104-section" style="background:#f6f8f7"><div class="v104-container"><div class="v109-section-head"><div><p class="v104-kicker">{{ __('site.treatments') }}</p><h2>{{ __('site.sample_specialties') }}</h2></div></div><div class="v109-specialty-list">@foreach($doctor->treatments as $specialty)<a href="{{ route('treatments.show',$specialty) }}"><img src="{{ specialty_visual_url($specialty) }}" alt="{{ $specialty->name }}" loading="lazy"><div><h3>{{ $specialty->name }}</h3><p>{{ $specialty->summary }}</p></div><b>{{ __('site.explore_short') }} →</b></a>@endforeach</div></div></section>@endif
@if($doctor->procedures->isNotEmpty())<section class="v104-section"><div class="v104-container"><div class="v109-section-head"><div><p class="v104-kicker">{{ __('site.library_badge') }}</p><h2>{{ __('site.treatments') }}</h2></div></div><div class="v109-priority-grid">@foreach($doctor->procedures->take(4) as $procedure)<a class="v109-priority-card" href="{{ route('procedures.show',[$procedure->specialty,$procedure]) }}"><img src="{{ procedure_visual_url($procedure) }}" alt="{{ $procedure->name }}" loading="lazy"><div><small>{{ $procedure->specialty?->name }}</small><h3>{{ $procedure->name }}</h3><p>{{ procedure_card_summary($procedure) }}</p><b>{{ __('site.view_guide') }} →</b></div></a>@endforeach</div></div></section>@endif
@endsection
