@foreach(['ar' => 'العربية'] as $locale => $label)
    @php($translation = $record?->translation($locale) ?? [])
    <section class="admin-translation-panel" dir="{{ $locale === 'ar' ? 'rtl' : 'ltr' }}">
        <p class="admin-overline">{{ $label }}</p>
        <p class="auth-help">Enter the {{ $label }} translation. These fields are empty by design so the admin can add approved content.</p>
        <div class="admin-form-grid"><label class="auth-field"><span>Name ({{ $label }})</span><input class="auth-input" name="name_{{ $locale }}" value="{{ old('name_'.$locale, $translation['name'] ?? '') }}"></label><label class="auth-field"><span>Summary ({{ $label }})</span><textarea class="auth-textarea compact" name="summary_{{ $locale }}">{{ old('summary_'.$locale, $translation['summary'] ?? '') }}</textarea></label></div>
        @if($type !== 'treatments')<label class="auth-field"><span>{{ $usesContent ? 'Full content' : 'Description' }} ({{ $label }})</span><textarea class="auth-textarea js-rich-text" name="{{ $usesContent ? 'content_'.$locale : 'description_'.$locale }}">{{ old(($usesContent ? 'content_' : 'description_').$locale, $translation[$usesContent ? 'content' : 'description'] ?? '') }}</textarea></label>@endif
        @if(in_array($type, ['patient-services', 'patient-stories'], true))<div class="auth-field bullet-points-editor" data-bullet-points-editor><span>Bullet points ({{ $label }})</span><small>Add one point per input.</small><div data-bullet-points-list>@foreach((array) ($translation['bullet_points'] ?? []) as $point)<div class="bullet-point-row"><input class="auth-input" name="bullet_points_{{ $locale }}[]" value="{{ $point }}" maxlength="255"><button class="auth-button danger" type="button" data-remove-bullet-point aria-label="Remove {{ $label }} bullet point">X</button></div>@endforeach</div><button class="auth-button secondary" type="button" data-add-bullet-point>Add point</button></div>@endif
        @if($type === 'patient-services')<label class="auth-field"><span>Primary action label ({{ $label }})</span><input class="auth-input" name="action_label_{{ $locale }}" maxlength="255" value="{{ old('action_label_'.$locale, $translation['action_label'] ?? '') }}"></label>@endif
        <p class="admin-overline">SEO ({{ $label }})</p><div class="admin-form-grid"><label class="auth-field"><span>SEO title</span><input class="auth-input" name="seo_title_{{ $locale }}" maxlength="60" value="{{ old('seo_title_'.$locale, $translation['seo_title'] ?? '') }}"></label><label class="auth-field"><span>SEO keywords</span><input class="auth-input" name="seo_keywords_{{ $locale }}" maxlength="500" value="{{ old('seo_keywords_'.$locale, $translation['seo_keywords'] ?? '') }}"></label><label class="auth-field"><span>Search visibility</span><select class="auth-select" name="seo_robots_{{ $locale }}"><option value="index,follow" @selected(old('seo_robots_'.$locale, $translation['seo_robots'] ?? $record?->seo_robots ?? 'index,follow') === 'index,follow')>Index and follow links</option><option value="noindex,nofollow" @selected(old('seo_robots_'.$locale, $translation['seo_robots'] ?? '') === 'noindex,nofollow')>Do not index</option></select></label></div><label class="auth-field"><span>Meta description</span><textarea class="auth-textarea compact" name="seo_description_{{ $locale }}" maxlength="160">{{ old('seo_description_'.$locale, $translation['seo_description'] ?? '') }}</textarea></label>
    </section>
@endforeach
