"""Point the 100 video modules at dedicated poster frames.

Each `--video-thumb` slot previously reused that page's procedure hero image, so
the video block rendered as a second copy of the banner immediately above it, and
nothing about it signalled "video". Dedicated 16:9 posters are generated by
`tools/build_artwork.py` into `assets/img/video/`.

The stylesheet also laid a 90%/74% gradient over the thumbnail, which buried it
almost completely. That is replaced here with a lighter, bottom-weighted scrim so
the poster reads while the overlaid heading and copy stay legible.

Run from the site root:  python3 tools/patch_video_thumbs.py
"""
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import sitecfg as cfg

CSS = """
/* --- 10. Video poster frames ------------------------------------------- */

/* template-fidelity.css sets `.conversion-video-v6 .video-placeholder` with
   !important on every declaration, including a flat
   linear-gradient(rgba(10,47,60,.83), rgba(10,47,60,.88)) over the thumbnail —
   at 83-88% the poster was invisible, and the caption was centred directly on
   top of the poster's play control. Matching that selector and specificity is
   the only way to override it without editing the original stylesheet. */
.conversion-video-v6 .video-placeholder,
.video-placeholder {
  background-image:
    linear-gradient(to top, rgba(8, 40, 58, 0.94) 0%, rgba(8, 40, 58, 0.82) 24%,
                    rgba(8, 40, 58, 0.12) 60%, rgba(8, 40, 58, 0.06) 100%),
    var(--video-thumb) !important;
  background-size: cover !important;
  background-position: center !important;
  display: flex !important;
  flex-direction: column !important;
  align-items: flex-start !important;
  justify-content: flex-end !important;
  text-align: left !important;
  padding: 32px 30px 28px !important;
  cursor: pointer;
  transition: background-image 0.25s;
}
.conversion-video-v6 .video-placeholder:hover,
.video-placeholder:hover {
  background-image:
    linear-gradient(to top, rgba(8, 40, 58, 0.90) 0%, rgba(8, 40, 58, 0.74) 24%,
                    rgba(8, 40, 58, 0.04) 60%, rgba(8, 40, 58, 0.02) 100%),
    var(--video-thumb) !important;
}
.conversion-video-v6 .video-placeholder h3,
.video-placeholder h3 {
  text-align: left !important;
  margin: 0 0 7px !important;
  font-size: 22px !important;
}
.conversion-video-v6 .video-placeholder p,
.video-placeholder p {
  text-align: left !important;
  margin: 0 !important;
  max-width: 560px;
  font-size: 13px;
  line-height: 1.55;
  color: #cfe6ee !important;
}
.video-consent-note {
  text-align: left !important;
}

/* The poster already draws a play control, so the text glyph is redundant.
   Kept in the DOM for assistive tech, hidden from sight. */
.video-placeholder .play.big {
  position: absolute !important;
  width: 1px !important;
  height: 1px !important;
  overflow: hidden !important;
  clip-path: inset(50%);
}
.video-placeholder:focus-visible {
  outline: 3px solid var(--blue);
  outline-offset: -3px;
}
"""


def patch_pages():
    n = 0
    for rel in cfg.html_files():
        if cfg.page_kind(rel) != "procedure":
            continue
        src = cfg.read(rel)
        spec = cfg.specialty_of(rel)
        slug = os.path.basename(rel)[:-5]
        thumb = "../img/video/thumb-%s-%s.svg" % (spec, slug)
        new, k = re.subn(r"--video-thumb:url\('[^']*'\)",
                         "--video-thumb:url('%s')" % thumb, src)
        if k:
            cfg.write(rel, new)
            n += 1
    print("  video posters wired into %d procedure pages" % n)


START = "/* v7:video-css:start */"
END = "/* v7:video-css:end */"


def add_css():
    """Replace the block rather than skipping when present. A guard that only
    appended on first run meant edits to CSS here silently never reached the
    stylesheet — the stale rules stayed and the change appeared not to work."""
    path = os.path.join(cfg.ROOT, "assets", "css", "v7-additions.css")
    with open(path, encoding="utf-8") as fh:
        css = fh.read()
    css = re.sub(re.escape(START) + ".*?" + re.escape(END), "", css, flags=re.S)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(css.rstrip() + "\n" + START + CSS + END + "\n")
    print("  video placeholder styles written")


if __name__ == "__main__":
    patch_pages()
    add_css()
