<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title', 'Admin | '.website_setting('brand.name'))</title>
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <link rel="alternate icon" href="{{ asset('favicon.svg') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/auth.css') }}">
    @stack('head')
</head>
<body class="admin-page">    @php        $user = auth()->user();        \App\Models\SitePage::seedDefaults();        $sidebarPages = \App\Models\SitePage::query()            ->orderByRaw("CASE WHEN slug = 'home' THEN 0 ELSE 1 END")            ->orderBy('title')            ->get();        $homeSidebarPage = $sidebarPages->firstWhere('slug', 'home');    @endphp    <div class="admin-shell">        <aside class="admin-sidebar">            <a class="brand" href="{{ route('home') }}">                <img alt="{{ website_setting('brand.name') }}" src="{{ website_logo_url() }}">            </a>            <div class="admin-sidebar-intro">                <span class="admin-overline">Content operations</span>                <strong>Admin workspace</strong>                <p>Publish a consistent patient journey from one calm, controlled workspace.</p>            </div>            <nav aria-label="Admin navigation">                <span class="admin-nav-label">Workspace</span>                <a class="{{ request()->routeIs('admin.dashboard') ? 'active' : '' }}" href="{{ route('admin.dashboard') }}">
<i>01</i>Dashboard</a>                <a class="{{ request()->routeIs('admin.inquiries.*') ? 'active' : '' }}" href="{{ route('admin.inquiries.index') }}">
<i>02</i>Inquiries</a>                <a class="{{ request()->routeIs('admin.treatment-requests.*') ? 'active' : '' }}" href="{{ route('admin.treatment-requests.index') }}">
<i>03</i>Treatment requests</a>                <span class="admin-nav-label">Publishing</span>                <a class="{{ request()->routeIs("admin.catalog.*") && request("type") === "treatments" ? "active" : "" }}" href="{{ route("admin.catalog.index", "treatments") }}"><i>04</i>{{ site_ui("treatments") }}</a>                <a class="{{ request()->routeIs("admin.labels.*") ? "active" : "" }}" href="{{ route("admin.labels.edit") }}"><i>05</i>English / German labels</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'procedures' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'procedures') }}"><i>05</i>Procedures</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'clinics' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'clinics') }}">
<i>06</i>Clinics</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'doctors' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'doctors') }}">
<i>07</i>Doctors</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'guides' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'guides') }}">
<i>08</i>Guides</a>                <details class="admin-pages-menu" @if(request()->routeIs('admin.pages.*')) open @endif>                    <summary class="{{ request()->routeIs('admin.pages.*') ? 'active' : '' }}">                        <span>
<i>09</i>Pages</span>                        <svg class="admin-pages-chevron" aria-hidden="true" viewBox="0 0 20 20" fill="currentColor">                            <path d="M5.23 7.21a1 1 0 0 1 1.41.02L10 10.59l3.36-3.36a1 1 0 1 1 1.41 1.41l-4.07 4.07a1 1 0 0 1-1.41 0L5.2 8.62a1 1 0 0 1 .03-1.41z" />                        </svg>                    </summary>                    <div class="admin-pages-submenu">                        <a class="{{ request()->routeIs('admin.pages.index') ? 'active' : '' }}" href="{{ route('admin.pages.index') }}">All pages</a>                        @if($homeSidebarPage)                            <a class="{{ request()->routeIs('admin.pages.edit') && request()->route('page')?->is($homeSidebarPage) ? 'active' : '' }}" href="{{ route('admin.pages.edit', $homeSidebarPage) }}">Home page</a>                        @endif                        @foreach($sidebarPages->reject(fn ($sidebarPage) => $sidebarPage->slug === 'home') as $sidebarPage)                            <a class="{{ request()->routeIs('admin.pages.edit') && request()->route('page')?->is($sidebarPage) ? 'active' : '' }}" href="{{ route('admin.pages.edit', $sidebarPage) }}">{{ $sidebarPage->title }}</a>                        @endforeach                    </div>                </details>                <a class="{{ request()->routeIs('admin.legal.*') ? 'active' : '' }}" href="{{ route('admin.legal.index') }}">
<i>10</i>Legal &amp; Privacy</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'patient-services' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'patient-services') }}">
<i>10</i>Patient services</a>                <a class="{{ request()->routeIs('admin.catalog.*') && request('type') === 'patient-stories' ? 'active' : '' }}" href="{{ route('admin.catalog.index', 'patient-stories') }}">
<i>11</i>Patient stories</a>                <span class="admin-nav-label">Account</span>                <a class="{{ request()->routeIs('profile.*') ? 'active' : '' }}" href="{{ route('profile.edit') }}">
<i>10</i>Profile</a>                <a class="{{ request()->routeIs('admin.settings.*') ? 'active' : '' }}" href="{{ route('admin.settings.edit') }}">
<i>11</i>Website settings</a>            </nav>            <div class="admin-user-card">
<span>{{ strtoupper(substr($user?->name ?? 'A', 0, 1)) }}</span>
<div>
<strong>{{ $user?->name ?? 'Admin' }}</strong>
<small>{{ $user?->email }}</small>
</div>
</div>        </aside>        <section class="admin-main">            <header class="admin-topbar">                <div>                    <span class="admin-overline">Turkelite Medcare</span>                    <strong>Content command center</strong>                </div>                <div class="auth-row">                    <a class="auth-button secondary" href="{{ route('home') }}">View public site</a>                    <form method="POST" action="{{ route('logout') }}">                        @csrf                        <button class="auth-button" type="submit">Log out</button>                    </form>                </div>            </header>            @isset($header)                <div class="admin-content">                    <div class="admin-card">                        {{ $header }}                    </div>                </div>            @endisset            <main class="admin-content">                {{ $slot }}            </main>        </section>    </div>    @stack('scripts')</body>
</html>
