@extends('layouts.site')
@section('title', __('site.doctors').' | Turkelite Medcare')
@section('description', __('site.presentation_notice'))
@section('robots', 'noindex,follow')
@section('content')
<section class="v109-split-hero"><div class="v104-container v109-split-grid"><div class="v109-split-copy"><p class="v104-kicker">{{ __('site.sample_profile') }}</p><h1>{{ __('site.meet_doctors') }}</h1><p>{{ __('site.presentation_notice') }} {{ __('site.verification_intro') }}</p><div class="v109-stat-row"><span>{{ $doctors->count() }} {{ __('site.sample_profile') }}</span><span>{{ __('site.before_publication') }}</span></div></div><figure class="v109-human-card"><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="Clinician reviewing a care plan with a patient" fetchpriority="high"><figcaption><small>{{ __('site.publication_gate') }}</small><strong>{{ __('site.before_publication') }}</strong><p>{{ __('site.verification_intro') }}</p></figcaption></figure></div></section>
<section class="v104-section"><div class="v104-container"><div class="v109-section-head"><div><p class="v104-kicker">{{ __('site.doctors') }}</p><h2>{{ __('site.sample_specialists') }}</h2></div><div><p>{{ __('site.profile_not_endorsement') }}</p></div></div><div class="v109-doctor-list">@forelse($doctors as $doctor)<a class="v109-doctor-card" href="{{ route('doctors.show',$doctor) }}"><div class="v109-avatar">{{ collect(preg_split('/\s+/',$doctor->name))->filter()->take(-2)->map(fn($p)=>mb_substr($p,0,1))->implode('') }}</div><small>{{ $doctor->treatments->pluck('name')->take(2)->implode(' · ') ?: __('site.sample_profile') }}</small><h3>{{ $doctor->name }}</h3><p>{{ $doctor->summary ?: $doctor->designation }}</p><span>{{ $doctor->clinic?->location ?: 'Turkey' }}@if($doctor->clinic) · {{ $doctor->clinic->name }}@endif</span></a>@empty<div class="v104-empty">{{ __('site.profiles_after_verification') }}</div>@endforelse</div></div></section>
<section class="v109-band"><div class="v104-container v109-band-grid"><div><p class="v104-kicker light">{{ __('site.next_step') }}</p><h2>{{ __('site.present_cta') }}</h2><p>{{ __('site.present_cta_text') }}</p><a class="v104-btn cn-btn-light" href="{{ route('treatment-plan') }}">{{ __('site.plan') }} →</a></div><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="International patient coordinator" loading="lazy"></div></section>
@endsection
