@extends('layouts.site')
@section('title', $page->seo_title ?: $page->title)
@section('description', $page->seo_description ?: $page->description)
@section('robots', $page->seo_robots ?: 'index,follow')
@section('content')
@php
$locale=app()->getLocale();
$copy=match($locale){
'de'=>[
'k'=>'Über Turkelite Medcare','title'=>'Wir koordinieren Ihre Behandlungsreise rund um medizinisch bestätigte Versorgung.','lead'=>'Wir helfen Ihnen, Optionen zu verstehen, Versorgungsumfelder zu vergleichen, die richtigen Fragen vorzubereiten und die praktischen Schritte verbunden zu halten. Diagnose, Einwilligung und Behandlung bleiben beim unabhängigen zugelassenen Anbieter.',
'why'=>'Warum es uns gibt','why_t'=>'Bei einer Behandlung im Ausland treffen medizinische Entscheidungen, Anbieterwahl, Kostenumfang, Reise und Nachsorge gleichzeitig aufeinander. Wir trennen diese Fragen sauber und halten die praktischen Übergaben zusammen.',
'do'=>'Was wir tun','do_t'=>'Wir strukturieren Behandlungsrecherche und Fragen, koordinieren Anbieterkommunikation, halten bestätigte Leistungen und Termine nachvollziehbar und organisieren die praktischen Reiseschritte rund um den medizinischen Plan.',
'dont'=>'Was wir nicht tun','dont_t'=>'Wir diagnostizieren nicht, entscheiden keine Eignung, empfehlen keine Behandlung als medizinische Notwendigkeit und führen keine Behandlung durch. Diese Verantwortung liegt beim unabhängigen, zugelassenen Anbieter.',
'model'=>'Wie das Geschäftsmodell funktioniert','model_t'=>'Unser Koordinationsmodell kann durch teilnehmende Anbieter finanziert werden, wenn über die Plattform eine Behandlung zustande kommt. Vor dem öffentlichen Launch müssen genaue Vergütung, mögliche Unterschiede zwischen Anbietern und die Regeln für bezahlte Sichtbarkeit transparent veröffentlicht werden. Medizinische Eignung darf nie von kommerziellen Bedingungen abhängen.',
'standard'=>'Unser Veröffentlichungsstandard für Anbieter','s1'=>'Rechtliche Identität','s1t'=>'Anbieteridentität und relevante Zulassungen werden vor öffentlicher Darstellung gegen geeignete Primärquellen geprüft.','s2'=>'Benannte Behandler','s2t'=>'Veröffentlichte Arztprofile sollen nachvollziehbare Qualifikation, Rolle und Anbieterzugehörigkeit enthalten.','s3'=>'Patientenweg','s3t'=>'Bewertung, Einwilligung, Sicherheits- und Nachsorgewege müssen vor Vermittlung eines Falls klar sein.','s4'=>'Behauptungen & Nachweise','s4t'=>'Akkreditierungen, Erfolgsangaben und medizinische Aussagen werden erst veröffentlicht, wenn sie belegbar und freigegeben sind.',
'cta'=>'Eine gute Reise beginnt mit einer klaren Zuständigkeit.','cta_t'=>'Wenn Sie eine Behandlung prüfen, beginnen wir mit Ihren Fragen – nicht mit einer Buchung.','button'=>'Behandlungsanfrage starten'],
'ar'=>[
'k'=>'عن Turkelite Medcare','title'=>'ننسق رحلة علاجك حول رعاية طبية تم تأكيدها سريرياً.','lead'=>'نساعدك على فهم الخيارات ومقارنة بيئات الرعاية وتجهيز الأسئلة الصحيحة وربط الخطوات العملية في مسار واحد. يبقى التشخيص والموافقة والعلاج مسؤولية مقدم الرعاية المستقل والمرخص.',
'why'=>'لماذا وُجدت هذه الخدمة','why_t'=>'العلاج في الخارج يجمع القرار الطبي واختيار مقدم الرعاية ونطاق التكلفة والسفر والمتابعة في وقت واحد. نفصل هذه الأسئلة بوضوح ونربط التسليمات العملية بينها.',
'do'=>'ما الذي نفعله','do_t'=>'ننظم البحث والأسئلة، وننسق التواصل مع مقدم الرعاية، ونوضح ما تم تأكيده من خدمات ومواعيد، ونرتب الخطوات العملية للسفر حول الخطة الطبية.',
'dont'=>'ما الذي لا نفعله','dont_t'=>'لا نشخص ولا نقرر الملاءمة ولا نقدم توصية طبية بضرورة إجراء معين ولا نقدم العلاج. تبقى هذه المسؤولية لدى مقدم الرعاية المستقل والمرخص.',
'model'=>'كيف يعمل النموذج التجاري','model_t'=>'قد يتم تمويل خدمة التنسيق من قبل مقدمي الرعاية المشاركين عند إتمام علاج عبر المنصة. قبل الإطلاق العام يجب نشر تفاصيل المقابل المالي وأي اختلافات بين مقدمي الرعاية وقواعد الظهور المدفوع بشفافية. ولا يجوز أن تتأثر الملاءمة الطبية بأي شروط تجارية.',
'standard'=>'معيارنا لنشر ملفات مقدمي الرعاية','s1'=>'الهوية القانونية','s1t'=>'يتم التحقق من هوية مقدم الرعاية والتراخيص ذات الصلة من مصادر أولية مناسبة قبل النشر العام.','s2'=>'الأطباء المسمّون','s2t'=>'يجب أن توضح ملفات الأطباء المنشورة مؤهلاتهم ودورهم وعلاقتهم بمقدم الرعاية بشكل قابل للتحقق.','s3'=>'مسار المريض','s3t'=>'يجب أن تكون إجراءات التقييم والموافقة والسلامة والمتابعة واضحة قبل توجيه الحالة.','s4'=>'الادعاءات والأدلة','s4t'=>'لا ننشر اعتماداً أو نتائج أو ادعاءات طبية قبل وجود دليل مناسب وموافقة للنشر.',
'cta'=>'الرحلة الجيدة تبدأ بمسؤوليات واضحة.','cta_t'=>'إذا كنت تدرس علاجاً، نبدأ بأسئلتك لا بالحجز.','button'=>'ابدأ استفسار العلاج'],
default=>[
'k'=>'About Turkelite Medcare','title'=>'We coordinate your treatment journey around clinically confirmed care.','lead'=>'We help you understand options, compare care environments, prepare the right questions and keep the practical steps connected. Diagnosis, consent and treatment remain with the independent licensed treating clinic and clinician.',
'why'=>'Why this service exists','why_t'=>'Treatment abroad puts clinical decisions, clinic choice, quotation scope, travel and follow-up into the same decision. We separate those questions clearly and keep the practical handovers connected.',
'do'=>'What we do','do_t'=>'We structure treatment research and questions, coordinate clinic communication, keep confirmed inclusions and dates visible, and organise the practical travel steps around the medical plan.',
'dont'=>'What we do not do','dont_t'=>'We do not diagnose, decide suitability, present a procedure as medically necessary or provide treatment. Those responsibilities belong to the independent licensed treating clinic and clinician.',
'model'=>'How the commercial model works','model_t'=>'Our coordination model may be funded by participating clinics when treatment is booked through the platform. Before public launch, the exact fee structure, any clinic-to-clinic differences and rules for paid visibility must be disclosed clearly. Clinical suitability must never be determined by commercial terms.',
'standard'=>'Our publication standard for providers','s1'=>'Legal identity','s1t'=>'Provider identity and relevant healthcare authorisations should be checked against appropriate primary sources before public publication.','s2'=>'Named clinicians','s2t'=>'Published doctor profiles should show verifiable qualifications, role and provider affiliation.','s3'=>'Patient pathway','s3t'=>'Assessment, consent, safety and follow-up routes should be clear before a case is routed.','s4'=>'Claims & evidence','s4t'=>'Accreditation, outcome claims and medical statements are published only when evidence and publication approval are available.',
'cta'=>'A good journey starts with clear responsibility.','cta_t'=>'If you are considering treatment, we start with your questions rather than a booking.','button'=>'Start treatment enquiry']};
@endphp
<section class="v104-content-hero"><div class="v104-container v104-content-hero-grid"><div><x-breadcrumbs :items="[['label'=>site_ui('home'),'url'=>route('home')],['label'=>site_ui('about')]]"/><p class="v104-kicker">{{ $copy['k'] }}</p><h1>{{ $copy['title'] }}</h1><p class="v104-lead">{{ $copy['lead'] }}</p></div><aside class="v104-principle-card"><span>{{ site_ui('provider_role') }}</span><div><b>{{ __('site.provider_title') }}</b><p>{{ __('site.provider_text') }}</p></div><div><b>{{ __('site.turkelite_title') }}</b><p>{{ __('site.turkelite_text') }}</p></div></aside></div></section>

<section class="v108-media-band"><div class="v104-container"><div class="v108-media-band-inner"><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="" loading="lazy" aria-hidden="true"><div class="v108-media-caption"><strong>{{ __('site.turkelite_title') }}</strong><p>{{ __('site.turkelite_text') }}</p></div></div></div></section>
<section class="v104-section"><div class="v104-container"><div class="v104-about-intro"><article><p class="v104-kicker">01</p><h2>{{ $copy['why'] }}</h2><p>{{ $copy['why_t'] }}</p></article><article><p class="v104-kicker">02</p><h2>{{ $copy['do'] }}</h2><p>{{ $copy['do_t'] }}</p></article><article><p class="v104-kicker">03</p><h2>{{ $copy['dont'] }}</h2><p>{{ $copy['dont_t'] }}</p></article></div></div></section>
<section class="v104-commercial"><div class="v104-container v104-commercial-grid"><p class="v104-kicker light">04 / {{ __('site.transparency') }}</p><div><h2>{{ $copy['model'] }}</h2><p>{{ $copy['model_t'] }}</p><a href="{{ route('legal.documents.show',['document'=>'terms.html']) }}">{{ site_footer('legal_privacy') }} ↗</a></div></div></section>
<section class="v104-section v104-check-section"><div class="v104-container"><div class="v104-heading-row compact"><div><p class="v104-kicker">05 / {{ __('site.publication_gate') }}</p><h2>{{ $copy['standard'] }}</h2></div></div><div class="v104-check-grid">@foreach([[$copy['s1'],$copy['s1t']],[$copy['s2'],$copy['s2t']],[$copy['s3'],$copy['s3t']],[$copy['s4'],$copy['s4t']]] as $item)<article><span>{{ str_pad((string)$loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div></div></section>
<section class="v104-end-cta"><div class="v104-container"><div><p class="v104-kicker">{{ site_ui('next_step') }}</p><h2>{{ $copy['cta'] }}</h2><p>{{ $copy['cta_t'] }}</p></div><a class="v104-btn v104-btn-dark" href="{{ route('treatment-plan') }}">{{ $copy['button'] }} ↗</a></div></section>
@endsection
