@extends('layouts.site')
@php
$locale=app()->getLocale();
$copy=match($locale){
'de'=>['title'=>'Kontakt','lead'=>'Beginnen Sie mit einer Frage. Unser Koordinationsteam ordnet die Informationen und führt Ihre Anfrage zum nächsten sinnvollen Schritt.','name'=>'Name','email'=>'E-Mail','phone'=>'Telefon / WhatsApp','subject'=>'Betreff','message'=>'Nachricht','consent'=>'Ich stimme zu, dass Turkelite Medcare mich zu dieser Anfrage kontaktiert.','privacy'=>'Datenschutzhinweis','send'=>'Anfrage senden','error'=>'Bitte prüfen Sie die markierten Felder.','routes'=>'Direkte Wege','plan'=>'Behandlungsanfrage','plan_text'=>'Wir strukturieren Ihre Anfrage, führen sie zur passenden Anbieterprüfung und koordinieren die Reiseplanung rund um bestätigte Termine.','whatsapp'=>'WhatsApp','whatsapp_text'=>'Für eine kurze erste Frage.','email_route'=>'E-Mail','email_text'=>'Für allgemeine Fragen ohne sensible medizinische Unterlagen.'],
'ar'=>['title'=>'تواصل معنا','lead'=>'ابدأ بسؤال واحد. يرتب فريق التنسيق المعلومات ويوجه استفسارك إلى الخطوة التالية المناسبة.','name'=>'الاسم','email'=>'البريد الإلكتروني','phone'=>'الهاتف / واتساب','subject'=>'الموضوع','message'=>'الرسالة','consent'=>'أوافق على أن تتواصل Turkelite Medcare معي بخصوص هذا الاستفسار.','privacy'=>'إشعار الخصوصية','send'=>'إرسال الاستفسار','error'=>'يرجى مراجعة الحقول المحددة.','routes'=>'طرق التواصل','plan'=>'طلب العلاج','plan_text'=>'نرتب طلبك ونوجهه للمراجعة المناسبة لدى مقدم الرعاية وننسق السفر حول المواعيد المؤكدة.','whatsapp'=>'واتساب','whatsapp_text'=>'لسؤال أولي قصير.','email_route'=>'البريد الإلكتروني','email_text'=>'للأسئلة العامة من دون إرسال سجلات طبية حساسة.'],
default=>['title'=>'Contact','lead'=>'Start with one question. Our coordination team organises the information and moves your enquiry toward the next sensible step.','name'=>'Name','email'=>'Email','phone'=>'Phone / WhatsApp','subject'=>'Subject','message'=>'Message','consent'=>'I agree to Turkelite Medcare contacting me about this enquiry.','privacy'=>'Privacy notice','send'=>'Send enquiry','error'=>'Please check the highlighted fields.','routes'=>'Direct routes','plan'=>'Treatment enquiry','plan_text'=>'We structure your request, route it for suitable provider review and coordinate travel planning around confirmed dates.','whatsapp'=>'WhatsApp','whatsapp_text'=>'For a short first question.','email_route'=>'Email','email_text'=>'For general questions without sending sensitive medical records.']};
@endphp
@section('title',$copy['title'].' | Turkelite Medcare')
@section('description',$copy['lead'])
@section('robots','index,follow,max-image-preview:large,max-snippet:-1')
@section('content')
<section class="v109-split-hero"><div class="v104-container v109-split-grid"><div class="v109-split-copy"><p class="v104-kicker">{{ __('site.support') }}</p><h1>{{ $copy['title'] }}</h1><p>{{ $copy['lead'] }}</p><div class="v109-stat-row"><span>{{ website_setting('brand.email') }}</span><span>{{ site_ui('medical_notice') }}</span></div></div><figure class="v109-human-card"><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="International patient coordinator" fetchpriority="high"><figcaption><small>{{ __('site.support') }}</small><strong>{{ $copy['plan'] }}</strong><p>{{ $copy['plan_text'] }}</p></figcaption></figure></div></section>
<section class="v104-section"><div class="v104-container v104-contact-layout"><div><p class="v104-kicker">{{ $copy['routes'] }}</p><div class="v109-route-grid"><a href="{{ route('treatment-plan') }}"><span>01</span><div><h3>{{ $copy['plan'] }}</h3><p>{{ $copy['plan_text'] }}</p></div><b>↗</b></a>@if(filled(website_setting('brand.whatsapp')))<a href="{{ website_setting('brand.whatsapp') }}" target="_blank" rel="noopener"><span>02</span><div><h3>{{ $copy['whatsapp'] }}</h3><p>{{ $copy['whatsapp_text'] }}</p></div><b>↗</b></a>@endif<a href="mailto:{{ website_setting('brand.email') }}"><span>03</span><div><h3>{{ $copy['email_route'] }}</h3><p>{{ $copy['email_text'] }}</p></div><b>↗</b></a></div></div>
<form class="v104-intake" method="POST" action="{{ route('contact.store') }}">@csrf<input type="hidden" name="type" value="contact"><input type="hidden" name="page_slug" value="contact">@if($errors->any())<div class="v104-form-alert error">{{ $copy['error'] }}</div>@endif<label>{{ $copy['name'] }}<input name="name" value="{{ old('name') }}" required autocomplete="name"></label><label>{{ $copy['email'] }}<input name="email" value="{{ old('email') }}" required type="email" autocomplete="email"></label><label>{{ $copy['phone'] }}<input name="phone" value="{{ old('phone') }}" type="tel" autocomplete="tel"></label><label>{{ $copy['subject'] }}<input name="subject" value="{{ old('subject') }}" required></label><label>{{ $copy['message'] }}<textarea name="message" required rows="6">{{ old('message') }}</textarea></label><label class="check"><input name="consent_processing" required type="checkbox" value="1"><span>{{ $copy['consent'] }} <a href="{{ route('legal.documents.show',['document'=>'privacy-policy.html']) }}">{{ $copy['privacy'] }}</a>.</span></label><button class="v104-btn v104-btn-dark" type="submit">{{ $copy['send'] }} ↗</button></form></div></section>
@endsection
