@extends('layouts.site')
@php
$locale=app()->getLocale();
$copy=match($locale){
'de'=>['k'=>'Partnerkliniken','title'=>'Eine klare Koordinationsschicht rund um Ihre medizinische Versorgung.','lead'=>'Wir suchen unabhängige, überprüfbare Anbieter, die internationale Patienten transparent informieren und Verantwortung sauber abgrenzen.','h'=>'Was vor einer Veröffentlichung geklärt sein muss','cta'=>'Partnergespräch starten'],
'ar'=>['k'=>'العيادات الشريكة','title'=>'طبقة تنسيق واضحة حول الرعاية الطبية التي تقدمونها.','lead'=>'نعمل مع مقدمي رعاية مستقلين يمكن التحقق منهم ويقدمون معلومات واضحة للمرضى الدوليين مع تحديد دقيق للمسؤوليات.','h'=>'ما الذي يجب التحقق منه قبل النشر','cta'=>'ابدأ محادثة شراكة'],
default=>['k'=>'Partner clinics','title'=>'A clear coordination layer around the care you provide.','lead'=>'We work with independent, verifiable providers that want international patients to receive clear information, responsible handovers and transparent scope.','h'=>'What must be clear before publication','cta'=>'Start a partner conversation']};
$items=match($locale){
'de'=>[['Identität & Zulassung','Rechtsträger und passende gesundheitliche Zulassungen prüfen.'],['Benannte Behandler','Klären, wer welche Eingriffe durchführt und wie Qualifikationen belegt werden.'],['Patientenpfad','Beurteilung, Einwilligung, Sicherheit, Leistungsumfang und Nachsorge dokumentieren.'],['Inhaltsfreigabe','Anbieterspezifische medizinische Aussagen und Qualifikationen werden vor Veröffentlichung geprüft.']],
'ar'=>[['الهوية والترخيص','التحقق من الكيان القانوني والتراخيص الصحية المناسبة.'],['الأطباء المسمّون','تحديد من يقوم بكل إجراء وكيف يتم إثبات مؤهلاته.'],['مسار المريض','توثيق التقييم والموافقة والسلامة ونطاق العرض ومسؤوليات المتابعة.'],['مراجعة المحتوى','تراجع الادعاءات الطبية ومؤهلات مقدم الرعاية قبل النشر.']],
default=>[['Identity & licensing','Verify the legal provider and appropriate healthcare authorisations.'],['Named clinicians','Confirm which clinicians perform which procedures and how their credentials are evidenced.'],['Patient pathway','Document assessment, consent, safety, quotation scope and follow-up responsibilities.'],['Content approval','Provider-specific medical claims and credentials are reviewed before publication.']]};
$meta=match($locale){
'de'=>['onboarding'=>'Partnerprüfung','flow'=>'Prüfen → abbilden → freigeben → veröffentlichen','role'=>'Die medizinische Verantwortung bleibt beim unabhängigen Anbieter; Turkelite koordiniert die praktische Patientenreise.','next'=>'Nächster Schritt','next_t'=>'Teilen Sie zunächst die Klinikidentität, Fachgebiete und benannten klinischen Kontakte. Die übrigen Nachweise können anschließend strukturiert werden.'],
'ar'=>['onboarding'=>'تأهيل الشريك','flow'=>'تحقق ← تنظيم ← اعتماد ← نشر','role'=>'تبقى المسؤولية الطبية لدى مقدم الرعاية المستقل؛ وتنسق Turkelite رحلة المريض العملية.','next'=>'الخطوة التالية','next_t'=>'ابدأ بإرسال هوية العيادة والتخصصات وجهات الاتصال السريرية المسماة. بعدها يمكن تنظيم بقية متطلبات التحقق.'],
default=>['onboarding'=>'Partner onboarding','flow'=>'Verify → map → approve → publish','role'=>'Medical responsibility remains with the independent provider; Turkelite coordinates the practical patient journey.','next'=>'Next step','next_t'=>'Share the clinic identity, specialties and named clinical contacts first. We can structure the remaining onboarding evidence from there.']};
@endphp
@section('title', $copy['k'].' | Turkelite Medcare')
@section('description', $copy['lead'])
@section('robots', 'noindex,follow')
@section('content')
<section class="v109-split-hero"><div class="v104-container v109-split-grid"><div class="v109-split-copy"><p class="v104-kicker">{{ $copy['k'] }}</p><h1>{{ $copy['title'] }}</h1><p>{{ $copy['lead'] }}</p><div class="v104-actions"><a class="v104-btn v104-btn-dark" href="{{ route('contact') }}">{{ $copy['cta'] }} ↗</a></div></div><figure class="v109-human-card"><img src="{{ asset('assets/img/final/specialty-general-surgery.webp') }}" alt="Illustrative care context" fetchpriority="high"><figcaption><small>{{ $meta['onboarding'] }}</small><strong>{{ $meta['flow'] }}</strong><p>{{ $meta['role'] }}</p></figcaption></figure></div></section>
<section class="v104-section"><div class="v104-container"><div class="v109-section-head"><div><p class="v104-kicker">{{ $meta['onboarding'] }}</p><h2>{{ $copy['h'] }}</h2></div></div><div class="v104-check-grid">@foreach($items as $item)<article><span>0{{ $loop->iteration }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div></div></section>
<section class="v109-band"><div class="v104-container v109-band-grid"><div><p class="v104-kicker light">{{ $meta['next'] }}</p><h2>{{ $copy['cta'] }}</h2><p>{{ $meta['next_t'] }}</p><a class="v104-btn cn-btn-light" href="{{ route('contact') }}">{{ $copy['cta'] }} →</a></div><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="Patient coordination team" loading="lazy"></div></section>
@endsection
