@extends('layouts.site')

@section('title', $page->seo_title ?: $page->title)
@section('description', $page->seo_description ?: $page->description)
@section('robots', $page->seo_robots ?: 'index,follow')

@section('content')
@php
$locale=app()->getLocale();
$copy=match($locale){
'de'=>[
'k'=>'Patientenservice','title'=>'Alles Praktische rund um die Behandlung – in einem Ablauf.','lead'=>'Sobald der behandelnde Anbieter den medizinischen Plan bestätigt, organisieren wir die praktische Reise darum – von Abholung und Flugplanung bis Unterkunft, Kliniktransfers, Rückreise und Nachsorgekoordination.',
'promise'=>'Was ein Koordinator zusammenhält','p1'=>'Anbieterkommunikation','p1t'=>'Wir halten Fragen, angeforderte Unterlagen, bestätigte Termine und offene Punkte an einem Ort nachvollziehbar.','p2'=>'Flug- & Reiseplanung','p2t'=>'Wir organisieren Flugzeiten und Reiseablauf rund um den medizinisch bestätigten Terminplan – niemals umgekehrt.','p3'=>'Abholung & Transfers','p3t'=>'Wir koordinieren vereinbarte Abholung zu Hause oder am Flughafen, lokale Kliniktransfers und die Rückfahrt nach bestätigten Terminen.','p4'=>'Hotel & Unterkunft','p4t'=>'Wir organisieren die Unterkunft nach Kliniklage, Aufenthaltsdauer, Erholungsbedarf und dem bestätigten Behandlungsplan.','p5'=>'Sprachliche Koordination','p5t'=>'Wir halten die praktische Kommunikation verständlich; medizinische Aufklärung muss durch den Anbieter erfolgen.','p6'=>'Nachsorgekoordination','p6t'=>'Wir bleiben während der Rückkehr der praktische Koordinationskontakt und halten Kontrolltermine, Warnzeichen und Klinikkontakte klar zusammen.',
'boundary'=>'Was der Service nicht ersetzt','boundary_t'=>'Turkelite Medcare ist keine Klinik, kein Notfalldienst und keine medizinische Zweitmeinung. Der behandelnde Anbieter bleibt für klinische Entscheidungen, Einwilligung, Behandlung und medizinische Nachsorge verantwortlich.',
'prep'=>'Vor der Abreise sollte der praktische Plan diese vier Dinge enthalten','q1'=>'Bestätigter medizinischer Ablauf','q1t'=>'Anbieter, Termine, erwartete Aufenthaltsdauer und offene medizinische Voraussetzungen.','q2'=>'Reiseplan von Tür zu Tür','q2t'=>'Abholung, Flüge, Unterkunft, Kliniktransfers, Rückreise und vereinbarter Rücktransfer oder Übergabepunkt.','q3'=>'Benannte Kontakte','q3t'=>'Koordinator, International Office der Klinik und der medizinische Kontakt für Fragen nach der Behandlung.','q4'=>'Rückkehrplan','q4t'=>'Dokumente, Kontrolltermine, Warnzeichen und klarer Kontaktweg nach der Heimreise.',
'cta'=>'Bauen wir den praktischen Plan erst, wenn die medizinische Route klar ist.','cta_t'=>'Starten Sie mit Ihrem Anliegen. Wir strukturieren die Informationen und organisieren den nächsten Schritt.','button'=>'Behandlungsanfrage starten'],
'ar'=>[
'k'=>'خدمات المرضى','title'=>'كل ما يحيط بالعلاج عملياً، في مسار واحد.','lead'=>'بعد أن يؤكد مقدم العلاج الخطة الطبية، ننظم الرحلة العملية حولها من الاستقبال وتوقيت الرحلات إلى الإقامة والتنقلات للعيادة والعودة وتنسيق المتابعة.',
'promise'=>'ما الذي يجمعه المنسق في مسار واحد','p1'=>'التواصل مع مقدم الرعاية','p1t'=>'نُبقي الأسئلة والسجلات المطلوبة والمواعيد المؤكدة والنقاط المفتوحة منظمة في مسار واحد.','p2'=>'الرحلات وخطة السفر','p2t'=>'ننظم توقيت الرحلات ومسار السفر حول الجدول الطبي المؤكد، وليس العكس.','p3'=>'الاستقبال والتنقلات','p3t'=>'ننسق الاستقبال المتفق عليه من المنزل أو المطار والتنقلات المحلية للعيادة والعودة حول المواعيد المؤكدة.','p4'=>'الفندق والإقامة','p4t'=>'ننظم الإقامة وفق موقع العيادة ومدة البقاء واحتياجات التعافي والجدول العلاجي المؤكد.','p5'=>'تنسيق اللغة','p5t'=>'نساعد على وضوح التواصل العملي؛ أما شرح العلاج والموافقة الطبية فمسؤولية مقدم الرعاية.','p6'=>'تنسيق المتابعة','p6t'=>'نبقى جهة التنسيق العملية خلال العودة، مع وضوح مواعيد المراجعة وعلامات التحذير وبيانات التواصل مع العيادة.',
'boundary'=>'ما الذي لا تستبدله هذه الخدمة','boundary_t'=>'Turkelite Medcare ليست عيادة ولا خدمة طوارئ ولا جهة تقدم رأياً طبياً ثانياً. يبقى مقدم الرعاية مسؤولاً عن القرارات السريرية والموافقة والعلاج والمتابعة الطبية.',
'prep'=>'قبل السفر، ينبغي أن تحتوي الخطة العملية على أربعة أمور','q1'=>'مسار طبي مؤكد','q1t'=>'مقدم الرعاية والمواعيد ومدة الإقامة المتوقعة وأي متطلبات طبية غير مكتملة.','q2'=>'مسار الرحلة من الباب إلى الباب','q2t'=>'الاستقبال والرحلات والإقامة والتنقلات للعيادة والعودة ونقطة التوصيل أو التسليم المتفق عليها.','q3'=>'جهات اتصال محددة','q3t'=>'المنسق ومكتب المرضى الدوليين في العيادة والجهة الطبية للأسئلة بعد العلاج.','q4'=>'خطة العودة','q4t'=>'التقارير والمراجعات وعلامات التحذير وطريقة التواصل بعد العودة.',
'cta'=>'نبني الخطة العملية بعد أن تصبح الخطة الطبية واضحة.','cta_t'=>'ابدأ بما تحتاجه. نرتب المعلومات وننظم الخطوة التالية.','button'=>'ابدأ استفسار العلاج'],
default=>[
'k'=>'Patient services','title'=>'Everything around the treatment, connected in one practical plan.','lead'=>'Once the treating provider confirms the medical plan, we organise the practical journey around it from pickup and flight timing to accommodation, clinic transfers, return travel and follow-up coordination.',
'promise'=>'What one coordinator keeps connected','p1'=>'Provider communication','p1t'=>'We keep questions, requested records, confirmed appointments and open points organised in one thread.','p2'=>'Flights & journey planning','p2t'=>'We organise flight timing and the practical itinerary around the medically confirmed schedule, never the other way around.','p3'=>'Pickup & transfers','p3t'=>'We coordinate agreed home or airport pickup, local clinic transfers and the return drop-off around confirmed appointments.','p4'=>'Hotel & accommodation','p4t'=>'We organise accommodation around the clinic location, expected stay, recovery needs and the confirmed care schedule.','p5'=>'Language coordination','p5t'=>'We help keep practical communication understandable; medical explanation and consent must come from the provider.','p6'=>'Aftercare coordination','p6t'=>'We stay as the practical coordination contact through the return-home handover, with review timing, warning signs and clinic contacts kept clear.',
'boundary'=>'What this service does not replace','boundary_t'=>'Turkelite Medcare is not a clinic, emergency service or medical second-opinion provider. The treating treating clinic remains responsible for clinical decisions, consent, treatment and medical follow-up.',
'prep'=>'Before departure, the practical plan should contain four things','q1'=>'Confirmed medical pathway','q1t'=>'Treating clinic, appointments, expected stay and any outstanding medical prerequisites.','q2'=>'Door-to-door journey itinerary','q2t'=>'Pickup, flights, accommodation, clinic transfers, return travel and the agreed drop-off or handover point.','q3'=>'Named contacts','q3t'=>'Your coordinator, the clinic’s international desk and the medical contact for post-treatment questions.','q4'=>'Return-home plan','q4t'=>'Documents, review timing, warning signs and a clear contact route after travel home.',
'cta'=>'Build the practical plan after the medical route is clear.','cta_t'=>'Start with your treatment need. We structure the information and organise the next step.','button'=>'Start treatment enquiry']};
$services=[[$copy['p1'],$copy['p1t']],[$copy['p2'],$copy['p2t']],[$copy['p3'],$copy['p3t']],[$copy['p4'],$copy['p4t']],[$copy['p5'],$copy['p5t']],[$copy['p6'],$copy['p6t']]];
@endphp
<section class="v104-content-hero"><div class="v104-container v104-content-hero-grid"><div><x-breadcrumbs :items="[['label'=>site_ui('home'),'url'=>route('home')],['label'=>site_ui('patient_services')]]"/><p class="v104-kicker">{{ $copy['k'] }}</p><h1>{{ $copy['title'] }}</h1><p class="v104-lead">{{ $copy['lead'] }}</p><div class="v104-actions"><a class="v104-btn v104-btn-dark" href="{{ route('treatment-plan') }}">{{ $copy['button'] }} ↗</a></div></div><aside class="v104-principle-card"><span>{{ site_ui('provider_role') }}</span><div><b>{{ __('site.provider_title') }}</b><p>{{ __('site.provider_text') }}</p></div><div><b>{{ __('site.turkelite_title') }}</b><p>{{ __('site.turkelite_text') }}</p></div></aside></div></section>

<section class="v108-media-band"><div class="v104-container"><div class="v108-media-band-inner"><img src="{{ asset('assets/img/v109/hero-patient.webp') }}" alt="" loading="lazy" aria-hidden="true"><div class="v108-media-caption"><strong>{{ __('site.journey_title') }}</strong><p>{{ __('site.what_we_do_lead') }}</p></div></div></div></section>

<section class="v104-section"><div class="v104-container"><div class="v104-heading-row compact"><div><p class="v104-kicker">01 / {{ __('site.what_we_do') }}</p><h2>{{ $copy['promise'] }}</h2></div></div><div class="v104-service-grid">@foreach($services as $item)<article><span>{{ str_pad((string)$loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div></div></section>

<section class="v104-boundary"><div class="v104-container"><p class="v104-kicker light">02 / {{ site_ui('provider_role') }}</p><div><h2>{{ $copy['boundary'] }}</h2><p>{{ $copy['boundary_t'] }}</p></div></div></section>

<section class="v104-section v104-check-section"><div class="v104-container"><div class="v104-heading-row compact"><div><p class="v104-kicker">03 / {{ site_ui('journey') }}</p><h2>{{ $copy['prep'] }}</h2></div></div><div class="v104-check-grid">@foreach([[$copy['q1'],$copy['q1t']],[$copy['q2'],$copy['q2t']],[$copy['q3'],$copy['q3t']],[$copy['q4'],$copy['q4t']]] as $item)<article><span>{{ str_pad((string)$loop->iteration,2,'0',STR_PAD_LEFT) }}</span><h3>{{ $item[0] }}</h3><p>{{ $item[1] }}</p></article>@endforeach</div></div></section>

<section class="v104-end-cta"><div class="v104-container"><div><p class="v104-kicker">{{ site_ui('next_step') }}</p><h2>{{ $copy['cta'] }}</h2><p>{{ $copy['cta_t'] }}</p></div><a class="v104-btn v104-btn-dark" href="{{ route('treatment-plan') }}">{{ $copy['button'] }} ↗</a></div></section>
@endsection
