@extends('layouts.site')
@php
    $locale = app()->getLocale();
    $content = $page->content ?? [];
    $copy = match($locale) {
        'de' => [
            'title'=>'Behandlungsanfrage starten','lead'=>'Sie müssen den genauen Eingriff noch nicht kennen. Teilen Sie uns Ihr Ziel oder Ihre Frage mit; wir ordnen die Informationen, klären was noch fehlt und führen die Anfrage zum nächsten sinnvollen Schritt.','reply'=>'Ihr Koordinator prüft Ihre Anfrage an Werktagen.','step'=>'Schritt','specialty'=>'Fachbereich','choose'=>'Fachbereich auswählen','concern'=>'Beschwerde oder Anliegen','concern_ph'=>'z. B. fehlende Zähne, Knieschmerzen, Haarausfall','procedure'=>'Behandlung von Interesse','optional'=>'optional','procedure_ph'=>'z. B. Zahnimplantate','about'=>'Über Sie','name'=>'Vollständiger Name','country'=>'Land','email'=>'E-Mail','phone'=>'Telefon / WhatsApp','language'=>'Bevorzugte Sprache','german'=>'Deutsch','english'=>'Englisch','arabic'=>'Arabisch','details'=>'Was sollten wir wissen?','medical'=>'Relevante Informationen','medical_ph'=>'Vorbehandlungen, bekannte Diagnose, Zeitrahmen, Fragen…','medical_note'=>'Teilen Sie nur Informationen, die für die erste Anfrage nützlich sind. Medizinische Unterlagen müssen hier noch nicht hochgeladen werden.','window'=>'Gewünschter Reise- oder Kontaktzeitraum','window_ph'=>'z. B. Oktober 2026 oder flexibel','consent'=>'Ich stimme zu, dass Turkelite Medcare diese Angaben zur Bearbeitung meiner Anfrage verarbeitet und mich dazu kontaktiert.','privacy'=>'Datenschutzhinweis','not_medical'=>'Diese Anfrage ist keine medizinische Beratung, begründet kein Arzt-Patienten-Verhältnis und ist nicht für Notfälle bestimmt.','back'=>'Zurück','next'=>'Weiter','submit'=>'Behandlungsanfrage senden','what_next'=>'Was passiert danach?','n1'=>'Wir prüfen Ihre Anfrage und klären, welche Informationen noch benötigt werden.','n2'=>'Falls Unterlagen benötigt werden, organisieren wir einen geeigneten sicheren Übermittlungsweg.','n3'=>'Wir identifizieren passende unabhängige Anbieter für eine erste Prüfung und halten Fragen und Antworten geordnet.','n4'=>'Medizinische Empfehlungen und Eignung werden ausschließlich vom behandelnden Anbieter bestätigt.','privacy_head'=>'Ihre Informationen zählen','privacy_text'=>'Wir sammeln in diesem ersten Schritt nur die Informationen, die zur Bearbeitung der Anfrage notwendig sind.','received'=>'Anfrage erhalten','error'=>'Bitte prüfen Sie die markierten Felder.'],
        'ar' => [
            'title'=>'ابدأ طلب العلاج','lead'=>'لا تحتاج إلى معرفة الإجراء الدقيق بعد. أخبرنا بالهدف أو السؤال؛ نحن نرتب المعلومات، نحدد ما يزال مطلوباً، ونوجه الاستفسار إلى الخطوة التالية المناسبة.','reply'=>'يراجع منسقك طلبك خلال أيام العمل.','step'=>'الخطوة','specialty'=>'التخصص','choose'=>'اختر التخصص','concern'=>'الحالة أو الهدف','concern_ph'=>'مثلاً: أسنان مفقودة، ألم في الركبة، تساقط الشعر','procedure'=>'العلاج الذي تفكر فيه','optional'=>'اختياري','procedure_ph'=>'مثلاً: زراعة الأسنان','about'=>'معلومات عنك','name'=>'الاسم الكامل','country'=>'البلد','email'=>'البريد الإلكتروني','phone'=>'الهاتف / واتساب','language'=>'اللغة المفضلة','german'=>'الألمانية','english'=>'الإنجليزية','arabic'=>'العربية','details'=>'ما المعلومات المفيدة؟','medical'=>'معلومات ذات صلة','medical_ph'=>'علاج سابق، تشخيص معروف، التوقيت، الأسئلة…','medical_note'=>'شارك فقط ما يساعد على فهم الاستفسار الأولي. لا تحتاج إلى رفع سجلات أو صور طبية في هذه المرحلة.','window'=>'الوقت المفضل للسفر أو التواصل','window_ph'=>'مثلاً: أكتوبر 2026 أو مرن','consent'=>'أوافق على أن تعالج Turkelite Medcare هذه البيانات لإعداد استفساري والتواصل معي بشأنه.','privacy'=>'إشعار الخصوصية','not_medical'=>'هذا الطلب لا يقدم استشارة طبية ولا ينشئ علاقة طبيب ومريض، وليس مخصصاً لحالات الطوارئ.','back'=>'رجوع','next'=>'متابعة','submit'=>'إرسال طلب العلاج','what_next'=>'ماذا يحدث بعد ذلك؟','n1'=>'نراجع طلبك ونحدد المعلومات التي ما زالت مطلوبة.','n2'=>'إذا كانت هناك حاجة إلى سجلات، نرتب لك طريقة آمنة ومناسبة لإرسالها.','n3'=>'نحدد مقدمي رعاية مستقلين مناسبين للمراجعة الأولية ونبقي الأسئلة والردود منظمة.','n4'=>'التوصية الطبية والملاءمة يؤكدهما مقدم الرعاية المعالج فقط.','privacy_head'=>'معلوماتك مهمة','privacy_text'=>'نجمع في هذه المرحلة الأولى فقط البيانات اللازمة لمعالجة الاستفسار.','received'=>'تم استلام الطلب','error'=>'يرجى مراجعة الحقول المحددة.'],
        default => [
            'title'=>'Build your treatment enquiry','lead'=>'You do not need to know the exact procedure yet. Tell us the goal or question; we organise the information, identify what is still needed and guide the enquiry to the next sensible step.','reply'=>'Your coordinator reviews your enquiry on working days.','step'=>'Step','specialty'=>'Specialty','choose'=>'Choose a specialty','concern'=>'Condition or concern','concern_ph'=>'e.g. missing teeth, knee pain, hair thinning','procedure'=>'Procedure of interest','optional'=>'optional','procedure_ph'=>'e.g. dental implants','about'=>'About you','name'=>'Full name','country'=>'Country','email'=>'Email','phone'=>'Phone / WhatsApp','language'=>'Preferred language','german'=>'German','english'=>'English','arabic'=>'Arabic','details'=>'What should we know?','medical'=>'Relevant information','medical_ph'=>'Previous treatment, known diagnosis, timing, questions…','medical_note'=>'Share only what helps us understand the initial enquiry. You do not need to upload records or scans at this stage.','window'=>'Preferred travel or contact window','window_ph'=>'e.g. October 2026 or flexible','consent'=>'I agree that Turkelite Medcare may process these details to prepare my enquiry and contact me about it.','privacy'=>'Privacy notice','not_medical'=>'This request does not provide medical advice, does not create a doctor-patient relationship and is not for emergencies.','back'=>'Back','next'=>'Continue','submit'=>'Submit treatment enquiry','what_next'=>'What happens next?','n1'=>'We review your enquiry and identify what information is still needed.','n2'=>'If records are needed, we arrange the appropriate secure route for them.','n3'=>'We identify suitable independent providers for an initial review and keep the questions and responses organised.','n4'=>'Medical recommendations and suitability are confirmed only by the treating provider.','privacy_head'=>'Your information matters','privacy_text'=>'At this first step we collect only the information needed to handle your enquiry.','received'=>'Request received','error'=>'Please check the highlighted fields.'],
    };
@endphp
@section('title', $copy['title'].' | Turkelite Medcare')
@section('description', $copy['lead'])
@section('robots', 'noindex,follow')

@section('content')
<section class="v104-form-hero"><div class="v104-container"><p class="v104-kicker">{{ __('site.next_step') }}</p><h1>{{ $copy['title'] }}</h1><p>{{ $copy['lead'] }}</p><div class="v104-form-proof"><span>{{ __('site.no_obligation') }}</span><span>{{ __('site.proof1') }}</span><span>{{ __('site.medical_notice') }}</span></div></div></section>
<section class="v104-form-section"><div class="v104-container v104-form-layout"><div>
@if(request()->filled('procedure'))
<div class="v108-context-banner"><span>{{ __('site.decision_snapshot') }}</span><div><strong>{{ request('procedure') }}</strong><p>{{ __('site.no_pressure') }} {{ __('site.request_review_text') }}</p></div></div>
@endif
@if(session('status'))<div class="v104-form-alert success"><b>{{ $copy['received'] }}</b><span>{{ session('status') }}</span></div>@endif
@if($errors->any())<div class="v104-form-alert error">{{ $copy['error'] }}</div>@endif
<form class="v104-intake" id="laravel-treatment-plan-form" method="POST" action="{{ route('treatment-plan.store') }}">@csrf
<input type="hidden" name="type" value="treatment-plan"><input type="hidden" name="page_slug" value="treatment-plan"><input type="hidden" name="subject" value="Treatment enquiry">
<div class="v104-reply"><b>{{ $copy['reply'] }}</b><span>{{ __('site.no_obligation') }}</span></div>
<div class="form-progress" aria-label="Progress"><span class="active" data-progress="1">1</span><i></i><span data-progress="2">2</span><i></i><span data-progress="3">3</span></div>
<div class="form-step active" data-step="1"><span class="v104-step-label">01 / {{ $copy['step'] }}</span><h2>{{ __('site.step1') }}</h2>
<label>{{ $copy['specialty'] }}<select name="specialty" required><option value="">{{ $copy['choose'] }}</option>@foreach($specialties as $specialty)<option value="{{ $specialty->name }}" @selected(old('specialty',$selectedSpecialty)===$specialty->slug || old('specialty')===$specialty->name)>{{ $specialty->name }}</option>@endforeach</select></label>
<label>{{ $copy['concern'] }}<input name="condition" value="{{ old('condition',request('condition')) }}" placeholder="{{ $copy['concern_ph'] }}"></label>
<label>{{ $copy['procedure'] }} <small>({{ $copy['optional'] }})</small><input id="procedure-input" name="procedure" value="{{ old('procedure',request('procedure')) }}" placeholder="{{ $copy['procedure_ph'] }}"></label>
<div class="step-actions"><button class="v104-btn v104-btn-dark" data-step-next type="button">{{ $copy['next'] }} →</button></div></div>
<div class="form-step" data-step="2" hidden><span class="v104-step-label">02 / {{ $copy['step'] }}</span><h2>{{ $copy['about'] }}</h2><div class="two-col"><label>{{ $copy['name'] }}<input name="name" value="{{ old('name') }}" autocomplete="name" required></label><label>{{ $copy['country'] }}<input name="country" value="{{ old('country') }}" autocomplete="country-name" required></label><label>{{ $copy['email'] }}<input name="email" type="email" value="{{ old('email') }}" autocomplete="email" required></label><label>{{ $copy['phone'] }}<input name="phone" type="tel" value="{{ old('phone') }}" autocomplete="tel"></label></div><label>{{ $copy['language'] }}<select name="preferred_language"><option value="English" @selected(old('preferred_language',$locale==='en'?'English':'')==='English')>{{ $copy['english'] }}</option><option value="German" @selected(old('preferred_language',$locale==='de'?'German':'')==='German')>{{ $copy['german'] }}</option><option value="Arabic" @selected(old('preferred_language',$locale==='ar'?'Arabic':'')==='Arabic')>{{ $copy['arabic'] }}</option></select></label><div class="step-actions"><button class="v104-btn v104-btn-plain" data-step-previous type="button">← {{ $copy['back'] }}</button><button class="v104-btn v104-btn-dark" data-step-next type="button">{{ $copy['next'] }} →</button></div></div>
<div class="form-step" data-step="3" hidden><span class="v104-step-label">03 / {{ $copy['step'] }}</span><h2>{{ $copy['details'] }}</h2><label>{{ $copy['medical'] }}<textarea name="message" rows="6" required placeholder="{{ $copy['medical_ph'] }}">{{ old('message') }}</textarea><small>{{ $copy['medical_note'] }}</small></label><label>{{ $copy['window'] }}<input name="preferred_time" value="{{ old('preferred_time') }}" placeholder="{{ $copy['window_ph'] }}"></label><label class="check"><input name="consent_processing" required type="checkbox" value="1" @checked(old('consent_processing'))><span>{{ $copy['consent'] }} <a href="{{ route('legal.documents.show',['document'=>'privacy-policy.html']) }}">{{ $copy['privacy'] }}</a>.</span></label><p class="v104-form-notice">{{ $copy['not_medical'] }}</p><div class="step-actions"><button class="v104-btn v104-btn-plain" data-step-previous type="button">← {{ $copy['back'] }}</button><button class="v104-btn v104-btn-dark" type="submit">{{ $copy['submit'] }} ↗</button></div></div>
</form></div>
<aside class="v104-form-aside"><div class="v109-contact-media"><img src="{{ asset('assets/img/v109/coordinator.webp') }}" alt="International patient coordinator" loading="lazy"></div><p class="v104-kicker">{{ $copy['what_next'] }}</p><ol><li><b>01</b>{{ $copy['n1'] }}</li><li><b>02</b>{{ $copy['n2'] }}</li><li><b>03</b>{{ $copy['n3'] }}</li><li><b>04</b>{{ $copy['n4'] }}</li></ol><div><b>{{ $copy['privacy_head'] }}</b><p>{{ $copy['privacy_text'] }}</p></div></aside>
</div></section>
@endsection

@push('scripts')
<script>(()=>{const form=document.getElementById('laravel-treatment-plan-form');if(!form)return;const steps=[...form.querySelectorAll('[data-step]')],markers=[...form.querySelectorAll('[data-progress]')];let current=1;const show=n=>{current=n;steps.forEach(s=>{const on=Number(s.dataset.step)===n;s.hidden=!on;s.classList.toggle('active',on)});markers.forEach(m=>m.classList.toggle('active',Number(m.dataset.progress)<=n));};form.querySelectorAll('[data-step-next]').forEach(btn=>btn.addEventListener('click',()=>{const active=steps.find(s=>Number(s.dataset.step)===current);const required=[...active.querySelectorAll('[required]')];for(const f of required){if(!f.checkValidity()){f.reportValidity();return}}show(Math.min(3,current+1));}));form.querySelectorAll('[data-step-previous]').forEach(btn=>btn.addEventListener('click',()=>show(Math.max(1,current-1))));@if($errors->any()) const errorFields=@json($errors->keys());const errorStep=errorFields.some(f=>['specialty','condition','procedure'].includes(f))?1:errorFields.some(f=>['name','country','email','phone','preferred_language'].includes(f))?2:3;show(errorStep);@endif})();</script>
@endpush
